Earnix_Naming_Convention = [
'PurchaseDate', 
'PurchasePrice', 
'Fee', 
'RetentionFlag', 
'PlanLiveCount', 
'PlansActivePast1yrCount', 
'PlansActivePast5yrCount', 
'PlansAcceptedPast1YearCount', 
'PlansAcceptedPast5YearCount', 
'PlansCancelledPast1YearCount', 
'PlansCancelledPast5YearCount', 
'ClaimPast1YearCount', 
'ClaimPast3YearCount', 
'ClaimPast5YearCount', 
'ClaimAmount1YearTotal',
'ClaimAmount3YearTotal',
'ClaimAmount5YearTotal',
'PrevRTPPriceType',
'BusinessEventCode',
'GoodsColour',
'ClientGroupDesc',
'SchemeTypeName',
'ClientAccountDesc',
'RouteToMarketName',
'CompanyCode',
'SchemeCode',
'ManufacturerGuaranteeLabourMonths',
'ManufacturerGuaranteePartsMonths',
'ApplianceCode',
'ClientGroupCode',
'ClientCode',
'ManufacturerBrandCode',
'Postcode_Sector'
]

rename_list = {
'AreaCode': 'areacode',
'HPI_AveragePrice': 'HPIAvgPrice',
'HPI_SalesVolume': 'HPISalesVolume',
'LAD_code': 'lad_code',
'LAD_name': 'lad_name',
'ONS_%people_working_49+': '%people_working_49+',
'ONS_%people_working_FT': '%people_working_FT',
'ONS_%people_working_sum': '%people_working_sum',
'ONS_avg_age': 'avg_age',
'ONS_avg_bedrooms': 'avg_bedrooms',
'ONS_avg_dependent_children_per_family': 'ons_avg_dependent_children_per_family',
'ONS_avg_distance_travelled_to_work(km)': 'avg_distance_travelled_to_work(km)',
'ONS_avg_household_size': 'avg_household_size',
'ONS_avg_rooms': 'avg_rooms',
'ONS_bedrooms per rooms': 'bedrooms per rooms',
'ONS_n_families': 'n_families',
'ONS_n_families/n_households': 'n_families_over_n_households',
'ONS_n_families_per_population': 'n_families_per_population',
'ONS_n_households': 'n_households',
'ONS_occupation_rate': 'occupation_rate',
'ONS_population': 'population',
'ONS_population_density': 'population_density',
'ONS_postcode_sector': 'ons_postcode_sector',
'PriceDiff%': 'pricediff%',
'RegionName': 'regionname',
'requested_buseventcode': 'BusinessEventCode',
'requested_claimamountfiveyeartotal': 'ClaimAmount5YearTotal',
'requested_claimamountoneyeartotal': 'ClaimAmount1YearTotal',
'requested_claimamountthreeyeartotal': 'ClaimAmount3YearTotal',
'requested_claimpastfiveyearcount': 'ClaimPast5YearCount',
'requested_claimpastoneyearcount': 'ClaimPast1YearCount',
'requested_claimpastthreeyearcount': 'ClaimPast3YearCount',
'claimsamount': 'claimsamount',
'claimscount': 'claimscount',
'requested_clientaccountdesc': 'ClientAccountDesc',
'requested_clientgroupdesc': 'ClientGroupDesc',
'requested_companycode': 'CompanyCode',
'contract_age': 'contract_age',
'contractcompanycode': 'contractcompanycode',
'contractcreateddate': 'contractcreateddate',
'contractdimensionid': 'contractdimensionid',
'contracteventdatetime': 'contracteventdatetime',
'contracteventdayssinceoffer': 'contracteventdayssinceoffer',
'contractnumber': 'contractnumber',
'contractschemecode': 'contractschemecode',
'contractstatuscode': 'contractstatuscode',
'country': 'country',
'datemonth': 'datemonth',
'dedup': 'dedup',
'diallerinteractionid': 'diallerinteractionid',
'diamond': 'diamond',
'requested_fee': 'Fee',
'gross': 'gross',
'itemcategoryname': 'itemcategoryname',
'itemcategoryname_dup': 'itemcategoryname_dup',
'itemdiamondcopyid': 'itemdiamondcopyid',
'itemdiamondcopyid_imputed': 'itemdiamondcopyid_imputed',
'itemdimensionid': 'itemdimensionid',
'itemgoldencopyid': 'itemgoldencopyid',
'requested_itemgoodscatcode': 'GoodsColour',
'itemgoodscategoryname': 'itemgoodscategoryname',
'itemlocationpostcode': 'itemlocationpostcode',
'itemlocationpostcode_dup': 'itemlocationpostcode_dup',
'itemmodelnumber': 'itemmodelnumber',
'itemmodelnumber_dup': 'itemmodelnumber_dup',
'itemmodelnumber_imputed': 'itemmodelnumber_imputed',
'itempurchasedatetime': 'itempurchasedatetime',
'itempurchaseprice': 'itempurchaseprice',
'itemserialnumber': 'itemserialnumber',
'itemsupercategorycode': 'itemsupercategorycode',
'manufacturerbrandname': 'manufacturerbrandname',
'manufacturerbrandname_dup': 'manufacturerbrandname_dup',
'manufacturergroupname': 'manufacturergroupname',
'modelid': 'modelid',
'movementdate': 'movementdate',
'offer_itemdimensionid': 'offer_itemdimensionid',
'offer_persondimensionid': 'offer_persondimensionid',
'offer_request_time': 'offer_request_time',
'offeracceptedindicator': 'offeracceptedindicator',
'offeracceptedprice': 'offeracceptedprice',
'offerbusinesseventcode': 'offerbusinesseventcode',
'offerbusinesseventsourcename': 'offerbusinesseventsourcename',
'offercampaignname': 'offercampaignname',
'offerchannelname': 'offerchannelname',
'offerclientname': 'offerclientname',
'offereffectivedatetime': 'CurrentDate',
'offereffectiveweek': 'offereffectiveweek',
'offerendofguaranteeflag': 'offerendofguaranteeflag',
'offermanufacturerendofguaranteedate': 'offermanufacturerendofguaranteedate',
'offerperiodofcover': 'offerperiodofcover',
'offerpostcode': 'offerpostcode',
'offerreferencenumber': 'offerreferencenumber',
'offersourcereceiveddatetime': 'offersourcereceiveddatetime',
'offerstatusname': 'offerstatusname',
'offertotalprice': 'offertotalprice',
'pcds': 'pcds',
'perh_id': 'perh_id',
'perhid': 'perhid',
'periodofcover': 'POC',
'person_persondimensionid': 'person_persondimensionid',
'requested_perpostaladdrpostcode': 'Postcode_Sector',
'persondisabilitycategory': 'persondisabilitycategory',
'persongender': 'persongender',
'persongoldencopyid': 'persongoldencopyid',
'persongoldencopyid_dup': 'persongoldencopyid_dup',
'personstatus': 'personstatus',
'planaccdate': 'planaccdate',
'requested_planlivecount': 'PlanLiveCount',
'planno': 'planno',
'requested_plansacceptedpastfiveyearcount': 'PlansAcceptedPast5YearCount',
'requested_plansacceptedpastoneyearcount': 'PlansAcceptedPast1YearCount',
'requested_plansactivepastfiveyearcount': 'PlansActivePast5yrCount',
'requested_plansactivepastoneyearcount': 'PlansActivePast1yrCount',
'requested_planscancelledpastfiveyearcount': 'PlansCancelledPast5YearCount',
'requested_planscancelledpastoneyearcount': 'PlansCancelledPast1YearCount',
'planstatus': 'planstatus',
'pmhid': 'pmhid',
'postcode_sector': 'postcode_sector',
'predictedconversionrate': 'predictedconversionrate',
'requested_prevrtppricetype': 'PrevRTPPriceType',
'prhidfk': 'prhidfk',
'PrhIdFk': 'prhidfk',
'price_dff_bands': 'price_dff_bands',
'price_diff': 'price_diff',
'pricingversiondescription': 'pricingversiondescription',
'rec_status': 'rec_status',
'recordstatus': 'recordstatus',
'region': 'region',
'requested_itemcode': 'ApplianceCode',
'requested_clientcode': 'ClientCode',
'requested_clientgroupcode': 'ClientGroupCode',
'requested_itemmanufbrandcode': 'ManufacturerBrandCode',
'requested_manugteeperiodlabourmonths': 'ManufacturerGuaranteeLabourMonths',
'requested_manugteeperiodpartsmonths': 'ManufacturerGuaranteePartsMonths',
'requested_purchaprice': 'PurchasePrice',
'requested_purchasedate': 'PurchaseDate',
'requested_retentionflag': 'RetentionFlag',
'requested_routetomarketname': 'RouteToMarketName',
'row_dedup': 'row_dedup',
'sale': 'sale',
'sale_dedup': 'sale_dedup',
'requested_schemecode': 'SchemeCode',
'requested_schemetypename': 'SchemeTypeName',
'totalprice': 'totalprice',
'year': 'year'
}

drop_list = ['areacode','regionname','claimsamount','claimscount','contract_age','contractcompanycode','contractcreateddate','contractdimensionid','contracteventdatetime','contracteventdayssinceoffer','contractnumber','contractschemecode','contractstatusname','datemonth','dedup','diallerinteractionid','diamond','gross'
               ,'itemcategoryname','itemcategoryname_dup','itemdiamondcopyid','itemdiamondcopyid_imputed','itemdimensionid','itemgoldencopyid','itemgoodscategoryname','itemlocationpostcode','itemlocationpostcode_dup','itemmodelnumber','itemmodelnumber_dup','itemmodelnumber_imputed','itempurchasedatetime','itempurchaseprice'
               ,'itemserialnumber','itemsupercategorycode','manufacturerbrandname','manufacturerbrandname_dup','manufacturergroupname','modelid','ModelId','offer_itemdimensionid','offer_persondimensionid','offer_request_time','offeracceptedindicator','offeracceptedprice','offerbusinesseventcode','offerbusinesseventsourcename'
               ,'offercampaignname','offerchannelname','offerclientname','offereffectiveweek','offerendofguaranteeflag','offermanufacturerendofguaranteedate','offerperiodofcover','offersourcereceiveddatetime','offerstatusname','pcds','perh_id','perhid','person_persondimensionid'
               ,'persondisabilitycategory','persongender','persongoldencopyid','persongoldencopyid_dup','personstatus','pmhid', 'PmhId','postcode_sector','prhidfk','price_dff_bands','pricediff%','rec_status','recordstatus','sale_dedup','year'
               , 'lad_code', 'lad_name', 'BusinessEventCode', 'ons_postcode_sector'
               , 'CompanyCode', 'SchemeCode', 'planno', 'planstatus', 'contractenddate', 'contractmovementdate'
               , 'contractoriginalstartdate', 'row_dedup', 'PerhId', 'RetentionFlag','itemeventuserid', 'schcode', 'year'
            #    ,'PeriodOfCover'
]

postcode_cols = [
    'offerpostcode',
    'pcds',
    'postcode_sector',
    'ONS_postcode_sector', 
    'perpostcodesector', 
    'perpostcodearea', 
    'LAD21NM',
    'Postcode_Sector',
    'itemlocationpostcode', # to comment out for pricing dataset
    'personaddresspostcode', # to comment out for pricing dataset
    'LAD_name',
    'LAD_code',
    'AreaCode',
    'RegionName',
    'region',
    'country']



# leaky features

leaky_feats = [
    'movementdate',
    'contractmonthyear',
    'offereventmonth',
    'contractmonth',
    'contractstatuscode',
    'planaccdate',
    'contract_age'
]

# redundant features

redundant_feats = [
    'sale',
    # 'item_price_bin',
    # 'claimpastfiveyearcount_bin',
    'startmonthyear',
    'offermonthyear',
    'offerreferencenumber',
    'startmonth',
    'year',
    'CurrentDate',
    'PurchaseDate',
    'SchemeTypeName',
    'RouteToMarketName' 
    ]